//! Zero Knowledge Proof Verifier Module
//!
//! Provides traits and implementations for ZK proof verification.
//! Compatible with ZoKrates-generated Groth16 proofs on BN254 curve.

use ark_bn254::{Bn254, Fr};
use ark_groth16::{prepare_verifying_key, Groth16, PreparedVerifyingKey, Proof, VerifyingKey};
use ark_serialize::CanonicalDeserialize;
use ark_snark::SNARK;
use ark_std::io::Cursor;
use thiserror::Error;

/// Errors that can occur during ZK proof verification
#[derive(Error, Debug)]
pub enum ZkVerifyError {
    #[error("Failed to deserialize proof: {0}")]
    ProofDeserializationError(String),

    #[error("Failed to deserialize public inputs: {0}")]
    InputDeserializationError(String),

    #[error("Failed to deserialize verifying key: {0}")]
    VerifyingKeyError(String),

    #[error("Proof verification failed")]
    VerificationFailed,

    #[error("Verifier not initialized with verifying key")]
    NotInitialized,
}

/// Result type for ZK verification operations
pub type ZkVerifyResult<T> = Result<T, ZkVerifyError>;

/// Trait for Zero Knowledge Proof verifiers
///
/// This trait abstracts the verification logic, allowing for different
/// implementations (real Groth16, mock for testing, etc.)
pub trait Verifier: Send + Sync {
    /// Verify a ZK proof against public inputs
    ///
    /// # Arguments
    /// * `proof` - Serialized proof bytes
    /// * `public_inputs` - Serialized public inputs bytes
    ///
    /// # Returns
    /// * `Ok(true)` if proof is valid
    /// * `Ok(false)` if proof is invalid
    /// * `Err(...)` if verification process fails
    fn verify(&self, proof: &[u8], public_inputs: &[u8]) -> ZkVerifyResult<bool>;

    /// Check if the verifier is properly initialized
    fn is_initialized(&self) -> bool;

    /// Get the verifier type name (for logging/debugging)
    fn verifier_type(&self) -> &'static str;
}

/// Groth16 Verifier for BN254 curve (ZoKrates compatible)
///
/// This verifier can validate proofs generated by ZoKrates or any other
/// system using Groth16 on the BN254 (alt_bn128) curve.
pub struct Groth16Verifier {
    prepared_vk: Option<PreparedVerifyingKey<Bn254>>,
}

impl Groth16Verifier {
    /// Create a new uninitialized verifier
    pub fn new() -> Self {
        Self { prepared_vk: None }
    }

    /// Initialize the verifier with a serialized verifying key
    ///
    /// # Arguments
    /// * `vk_bytes` - Serialized verifying key (from ZoKrates export)
    pub fn init_with_key(&mut self, vk_bytes: &[u8]) -> ZkVerifyResult<()> {
        let mut cursor = Cursor::new(vk_bytes);
        let vk = VerifyingKey::<Bn254>::deserialize_compressed(&mut cursor)
            .map_err(|e| ZkVerifyError::VerifyingKeyError(e.to_string()))?;

        self.prepared_vk = Some(prepare_verifying_key(&vk));

        Ok(())
    }

    /// Deserialize a Groth16 proof from bytes
    fn deserialize_proof(proof_bytes: &[u8]) -> ZkVerifyResult<Proof<Bn254>> {
        let mut cursor = Cursor::new(proof_bytes);
        Proof::deserialize_compressed(&mut cursor)
            .map_err(|e| ZkVerifyError::ProofDeserializationError(e.to_string()))
    }

    /// Deserialize public inputs from bytes
    fn deserialize_inputs(input_bytes: &[u8]) -> ZkVerifyResult<Vec<Fr>> {
        let mut cursor = Cursor::new(input_bytes);
        Vec::<Fr>::deserialize_compressed(&mut cursor)
            .map_err(|e| ZkVerifyError::InputDeserializationError(e.to_string()))
    }
}

impl Default for Groth16Verifier {
    fn default() -> Self {
        Self::new()
    }
}

impl Verifier for Groth16Verifier {
    fn verify(&self, proof: &[u8], public_inputs: &[u8]) -> ZkVerifyResult<bool> {
        let pvk = self
            .prepared_vk
            .as_ref()
            .ok_or(ZkVerifyError::NotInitialized)?;

        let proof = Self::deserialize_proof(proof)?;
        let inputs = Self::deserialize_inputs(public_inputs)?;

        let is_valid = Groth16::<Bn254>::verify_with_processed_vk(pvk, &inputs, &proof)
            .map_err(|_| ZkVerifyError::VerificationFailed)?;

        Ok(is_valid)
    }

    fn is_initialized(&self) -> bool {
        self.prepared_vk.is_some()
    }

    fn verifier_type(&self) -> &'static str {
        "Groth16-BN254"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_groth16_verifier_not_initialized() {
        let verifier = Groth16Verifier::new();
        assert!(!verifier.is_initialized());

        let result = verifier.verify(&[0u8; 32], &[0u8; 32]);
        assert!(matches!(result, Err(ZkVerifyError::NotInitialized)));
    }

    #[test]
    fn test_verifier_type() {
        let verifier = Groth16Verifier::new();
        assert_eq!(verifier.verifier_type(), "Groth16-BN254");
    }
}
